markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block_code_output_to_label: true
    span_code_output_to_label: false

title: GitLessons
baseurl: "/College-lessons"
url: "" 

collections:
  python_lessons:
    output: true
    permalink: /python/:name
    back_link: "python.html" 
  php_lessons:
    output: true
    permalink: /php/:name
    back_link: "php.html"

defaults:
  - scope:
      path: ""
      type: "python_lessons"
    values:
      layout: "lesson"
  - scope:
      path: ""
      type: "php_lessons"
    values:
      layout: "lesson"

